# Generated by Django 2.2.4 on 2019-08-23 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nangroupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(default='nanlogo.jpg', upload_to='pic_folder/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=20, null=True)),
                ('contacts', models.CharField(max_length=30, null=True)),
                ('qrcontent', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(default='useravatar.jpg', upload_to='pic_folder/')),
                ('userkey', models.IntegerField(null=True)),
                ('userckey', models.CharField(max_length=255, null=True)),
                ('userpass', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=30, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usergroupe', to='presence.Nangroupe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
