# Generated by Django 2.2.4 on 2019-08-23 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='groupe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usergroupe', to='presence.Nangroupe'),
        ),
    ]
