# Generated by Django 2.2.4 on 2019-08-23 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presence', '0002_auto_20190823_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jours', models.DateField()),
                ('image', models.ImageField(default='nanlogo.png', upload_to='pic_folder/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='nangroupe',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nangroupe',
            name='image',
            field=models.ImageField(default='nanlogo.png', upload_to='pic_folder/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='useravatar.png', upload_to='pic_folder/'),
        ),
    ]
