# Generated by Django 2.2.4 on 2019-08-23 11:53

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0005_auto_20190823_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='jours',
            name='debut_heure_arrivee',
            field=models.TimeField(default='08:00', null=True),
        ),
        migrations.AddField(
            model_name='jours',
            name='fin_heure_arrivee',
            field=models.TimeField(default='10:00', null=True),
        ),
        migrations.AddField(
            model_name='jours',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='nan', editable=False, populate_from=models.DateField(), unique_with=['created_by__username', 'debut_heure_arrivee']),
            preserve_default=False,
        ),
    ]
