# Generated by Django 2.2.4 on 2019-08-23 12:00

from django.db import migrations
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0006_auto_20190823_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jours',
            name='slug',
            field=slugger.fields.AutoSlugField(populate_from='jours'),
        ),
    ]
