# Generated by Django 2.2.4 on 2019-08-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0008_auto_20190823_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jours',
            name='slug',
            field=models.TextField(null=True, unique=True),
        ),
    ]
