# Generated by Django 2.2.4 on 2019-08-23 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presence', '0009_auto_20190823_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jours',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_arrivee', models.TimeField(null=True)),
                ('heure_depart', models.TimeField(default='17:00', null=True)),
                ('statut', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joursap', to='presence.Jours')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userpresence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'jours')},
            },
        ),
    ]
