# Generated by Django 2.2.4 on 2019-08-25 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presence', '0010_auto_20190823_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jours_cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('statut', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='nangroupe',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nangroupe',
            name='etudiants',
            field=models.ManyToManyField(related_name='useringroup', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nangroupe',
            name='responsables',
            field=models.ManyToManyField(related_name='respogroup', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nangroupe',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creerpar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nangroupe',
            name='jours_presence',
            field=models.ManyToManyField(to='presence.Jours_cours'),
        ),
    ]
