# Generated by Django 2.2.4 on 2019-09-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0011_auto_20190825_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='jours_cours',
            name='weekday',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
