# Generated by Django 2.2.4 on 2019-09-08 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presence', '0013_nangroupe_equipe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('statut', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.TextField()),
                ('statut', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('duree_du_quiz', models.PositiveIntegerField(default=10)),
                ('cota_validation', models.PositiveIntegerField(default=70)),
                ('positonduquiz', models.BooleanField(default=True)),
                ('statut', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groupe_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizgroup', to='presence.Nangroupe')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('statut', models.BooleanField(default=True)),
                ('type_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typequestion', to='specialisation.QuestionType')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('source', models.FileField(upload_to='projet/')),
                ('cota_validation', models.PositiveIntegerField(default=70)),
                ('statut', models.BooleanField(default=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groupe_projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetgroup', to='presence.Nangroupe')),
            ],
        ),
        migrations.CreateModel(
            name='CompositionQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.BooleanField(default=False)),
                ('note', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz_compo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compoquiz', to='specialisation.Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiztuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompositionProjet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien', models.URLField()),
                ('statut', models.BooleanField(default=False)),
                ('note', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_compo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compoprojet', to='specialisation.Projet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
